about us page started
Zunuoh/fino pull request #3
Opened 2022-06-24 20:57 UTC by Zunuoh

2022-06-25 17:49 UTC, claeusdev requested changes
Overall this looks good, just a few comments:

1. You should endeavor to use `.js` extensions for pure javascript functionality and then `jsx` for your components. Easy for anyone who picks up your work to know the difference between the two. see [here](https://github.com/airbnb/javascript#references) for example best practices.
2. Looking at your `Aboutus` components, you could really break it down into much smaller bits that you can compose to build bigger components/pages. 
3. [This](https://github.com/airbnb/javascript/tree/master/react#airbnb-reactjsx-style-guide) is one of the places I've used to get some best practices and also help me understand some of the decisions. 
4. Finally, please always remember to open PRs like this and make them small also like this. This way it'll be very easy to review and give some quality feedback.

2022-06-25 17:49 UTC, claeusdev commented on src/App.js
> +import Aboutus from "./components/aboutus/Aboutus";
It's always good to name your top-level components using `CamelCase`.

Also to be able to separate concerns, ie: grouping things related to their intended purpose. Components that are "pages" should be placed under a top-level directory eg. `pages/AboutUs`. `components` should be used for things that are reusable and I don't think you're going to be reusing the about page a whole lot.

The benefit of this is that you're going easily figure out where things are.

2022-06-25 17:49 UTC, claeusdev commented on src/components/aboutus/Aboutus.js
> +    <div style ={{}}>
Remember to always remove empty braces from code.

2022-06-30 17:32 UTC, claeusdev approved these changes
LGTM .. Looks great.

2022-07-01 08:26 UTC, Zunuoh commented
Thanks

Sent from my iPhone

> On Jun 30, 2022, at 17:32, Nana Adjei Manu ***@***.***> wrote:
> 
> ﻿
> @claeusdev approved this pull request.
> 
> LGTM .. Looks great.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-07-01 15:54 UTC, merged